[package]
name = "rcut"
version = "0.1.0"
authors = ["Chip Turner <cturner@pattern.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
anyhow = "1.0"
itertools = "0.8"