[package]
name = "rcut"
version = "0.1.0"
authors = ["Chip Turner <cturner@pattern.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1"
anyhow = "1.0"
itertools = "0.10"